pool:
  name: Hosted Windows 2019 with VS2019
##Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
variables:
  NUGET_PACKAGES: '$(Build.SourcesDirectory)\.nuget\packages'
  BuildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.106'
  inputs:
    version: 2.2.106

- task: PowerShell@2
  displayName: 'dotnet restore, build, test and publish'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    arguments: '$(BuildConfiguration) $(Build.SourcesDirectory) $(build.stagingDirectory)'
 
- task: PublishTestResults@2
  displayName: 'Publish Test Results **\testresults.xml'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**\testresults.xml'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\partsunlimited.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: ARMTemplates'
  inputs:
    PathtoPublish: env/Templates
    ArtifactName: ARMTemplates
